version: "3"
x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'
include:
  - "supabase/docker-compose.yml"
services:
  # neroshitron:
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000

  owncast:
    image: owncast/owncast:latest
    restart: unless-stopped
    ports:
      - 8080:8080
      - 1935:1935
    volumes:
      - ./data:/owncast/data

  maildev:
    image: maildev/maildev:latest
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
    volumes:
      - ./data:/maildev/data
      
volumes:
  db-config:
